"""cria tabelas iniciais

Revision ID: 494d7cb2cbc5
Revises: 
Create Date: 2026-03-12 20:42:44.591297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '494d7cb2cbc5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id_categoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_categoria', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('cor_hex', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria'),
    sa.UniqueConstraint('nome_categoria')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_usuario', sa.Enum('CIDADAO', 'ADMIN', name='tipousuario'), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('nome_usuario', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=11), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('status_ativo', sa.Boolean(), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('solicitacao',
    sa.Column('id_solicitacao', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_autor', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('protocolo', sa.String(length=12), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('endereco_referencia', sa.String(length=300), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'EM_ANALISE', 'EM_ANDAMENTO', 'RESOLVIDO', 'CANCELADO', name='statussolicitacao'), nullable=False),
    sa.Column('contador_apoios', sa.Integer(), nullable=False),
    sa.Column('data_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_resolucao', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_autor'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id_categoria'], ),
    sa.PrimaryKeyConstraint('id_solicitacao'),
    sa.UniqueConstraint('protocolo')
    )
    op.create_table('apoio',
    sa.Column('id_apoio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_solicitacao', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('data_apoio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_solicitacao'], ['solicitacao.id_solicitacao'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_apoio'),
    sa.UniqueConstraint('id_solicitacao', 'id_usuario')
    )
    op.create_table('atualizacao',
    sa.Column('id_atualizacao', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_solicitacao', sa.Integer(), nullable=False),
    sa.Column('id_administrador', sa.Integer(), nullable=True),
    sa.Column('status_anterior', sa.Enum('PENDENTE', 'EM_ANALISE', 'EM_ANDAMENTO', 'RESOLVIDO', 'CANCELADO', name='statussolicitacao'), nullable=False),
    sa.Column('status_novo', sa.Enum('PENDENTE', 'EM_ANALISE', 'EM_ANDAMENTO', 'RESOLVIDO', 'CANCELADO', name='statussolicitacao'), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_administrador'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_solicitacao'], ['solicitacao.id_solicitacao'], ),
    sa.PrimaryKeyConstraint('id_atualizacao')
    )
    op.create_table('avaliacao',
    sa.Column('id_avaliacao', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_solicitacao', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('foi_resolvido', sa.Boolean(), nullable=False),
    sa.Column('nota', sa.SmallInteger(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('data_avaliacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_solicitacao'], ['solicitacao.id_solicitacao'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_avaliacao'),
    sa.UniqueConstraint('id_solicitacao')
    )
    op.create_table('foto',
    sa.Column('id_foto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_solicitacao', sa.Integer(), nullable=False),
    sa.Column('caminho_arquivo', sa.String(length=500), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_solicitacao'], ['solicitacao.id_solicitacao'], ),
    sa.PrimaryKeyConstraint('id_foto')
    )
    op.create_table('notificacao',
    sa.Column('id_notificacao', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_solicitacao', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.String(length=300), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_solicitacao'], ['solicitacao.id_solicitacao'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_notificacao')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificacao')
    op.drop_table('foto')
    op.drop_table('avaliacao')
    op.drop_table('atualizacao')
    op.drop_table('apoio')
    op.drop_table('solicitacao')
    op.drop_table('usuario')
    op.drop_table('categoria')
    # ### end Alembic commands ###
